/**
 *  Copyright (c) 2025, Ajxs.
 *  SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef TRAPS_H
#define TRAPS_H

#define PCB_OFFSET_KERNEL_CONTEXT 0
#define KERNEL_CONTEXT_SIZE (14 * 8)
#define KERNEL_CONTEXT_OFFSET_SP (PCB_OFFSET_KERNEL_CONTEXT + (1 * 8))
#define PCB_OFFSET_TRAP_CONTEXT (PCB_OFFSET_KERNEL_CONTEXT + KERNEL_CONTEXT_SIZE)
#define TRAP_CONTEXT_SIZE (68 * 8)

#define PCB_OFFSET_USER_SP (PCB_OFFSET_TRAP_CONTEXT + TRAP_CONTEXT_SIZE)

#define TRAP_CONTEXT_OFFSET_SEPC 512
#define TRAP_CONTEXT_OFFSET_SSTATUS 520
#define TRAP_CONTEXT_OFFSET_SCAUSE 528
#define TRAP_CONTEXT_OFFSET_TP 536

#endif
