#ifndef STRAYLIGHT_LIBC_SYSCALL_H
#define STRAYLIGHT_LIBC_SYSCALL_H

#define STRAYLIGHT_SYSCALL_SUCCESS         0
#define STRAYLIGHT_SYSCALL_FAILURE         1

#define STRAYLIGHT_SYSCALL_ALLOCATE_MEMORY 54460004
#define STRAYLIGHT_SYSCALL_PROCESS_EXIT    54460000

#endif
